/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.codebro.fortress.system.persistence.po;

import cn.codebro.fortress.common.model.BaseEntity;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

/**
 * @project fortress-admin
 * @author Guo Wentao
 * @version 1.0.0
 * Table: f_role 	
 */
@Entity(tableName = "f_role", comment = "", pk_constraint = "PRIMARY")
public class FRolePO extends BaseEntity {
    /**
     *
     */
    private static final long serialVersionUID = 2991438475977648019L;

    /**
     * 主键
     */
    @Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.NanoTimeIdGenerator")
    @Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nullable = false)
    protected String id;
    /**
     * 角色名
     */
    @Column(name = "name", comment = "角色名", length = 200L, type = java.sql.Types.VARCHAR, nullable = true)
    protected String name;
    /**
     * 角色标识
     */
    @Column(name = "identify", comment = "角色标识", length = 200L, type = java.sql.Types.VARCHAR, nullable = true)
    protected String identify;
    /**
     * 排序
     */
    @Column(name = "order_num", comment = "排序", length = 10L, type = java.sql.Types.INTEGER, nullable = true)
    protected Integer orderNum;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdentify() {
        return identify;
    }

    public void setIdentify(String identify) {
        this.identify = identify;
    }

    @Override
    public Integer getOrderNum() {
        return orderNum;
    }

    @Override
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}
