/**
 * @Generated by sagacity-quickvo 5.0
 */
package cn.codebro.fortress.system.persistence.po;

import cn.codebro.fortress.common.model.BaseEntity;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

/**
 * @project fortress-admin
 * @author Guo Wentao
 * @version 1.0.0
 * Table: f_role_auth 	
 */
@Entity(tableName = "f_role_auth", comment = "", pk_constraint = "PRIMARY")
public class FRoleAuthPO extends BaseEntity {

    /**
     * 主键
     */
    @Id(strategy = "generator", generator = "org.sagacity.sqltoy.plugins.id.impl.NanoTimeIdGenerator")
    @Column(name = "id", comment = "主键", length = 32L, type = java.sql.Types.VARCHAR, nullable = false)
    protected String id;
    /**
     * 角色id
     */
    @Column(name = "role_id", comment = "角色id", length = 32L, type = java.sql.Types.VARCHAR, nullable = true)
    protected String roleId;
    /**
     * 权限id
     */
    @Column(name = "auth_id", comment = "权限id", length = 32L, type = java.sql.Types.VARCHAR, nullable = true)
    protected String authId;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getAuthId() {
        return authId;
    }

    public void setAuthId(String authId) {
        this.authId = authId;
    }
}
