/**
 *@Generated by sagacity-quickvo 5.0
 */
package cn.codebro.fortress.system.persistence.po;

import cn.codebro.fortress.common.model.BaseEntity;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.time.LocalDateTime;

/**
 * @project fortress-admin
 * @author Guo Wentao
 * @version 1.0.0
 * Table: f_system 	
 */
@Entity(tableName="f_system",comment="",pk_constraint="PRIMARY")
public class FSystemPO extends BaseEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 8613977610745152803L;


	/**
	 * jdbcType:VARCHAR
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.NanoTimeIdGenerator")
	@Column(name="id",comment="",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String id;
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="system_name",comment="",length=200L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String systemName;
	/**
	 * jdbcType:BIT
	 */
	@Column(name="initialized",comment="",length=1L,type=java.sql.Types.BIT,nullable=true)
	protected Boolean initialized;
	/**
	 * jdbcType:DATETIME
	 */
	@Column(name="initialize_time",comment="",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime initializeTime;
	/**
	 * jdbcType:INT
	 */
	@Column(name="version",comment="",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer version;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	public Boolean getInitialized() {
		return initialized;
	}

	public void setInitialized(Boolean initialized) {
		this.initialized = initialized;
	}

	public LocalDateTime getInitializeTime() {
		return initializeTime;
	}

	public void setInitializeTime(LocalDateTime initializeTime) {
		this.initializeTime = initializeTime;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
}
